title: Giltri Songia Rafel # your name (or website title) here
logo: "/images/logo.png?" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>I am currently a Data Warehousing, Analysis, and Visualization for Business Insights at Zenius.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
